cluster.name: "docker-cluster"
network.host: 0.0.0.0

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1

searchguard.authcz.admin_dn:
  - CN=spock, OU=client, O=client, L=Test, C=DE
searchguard.nodes_dn:
  - CN=*.example.com,OU=SSL,O=Test,L=Test,C=DE
